version: "3.9"
services:
  base:
    build:
      context: ./base-image
    image: flight-base:latest

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8003"
    depends_on:
      - base

  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - "8001:8001"
    depends_on:
      - base

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8002:8002"
    depends_on:
      - base

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8004:8004"
    depends_on:
      - base
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - flight-service
      - booking-service
      - payment-service

  postgres:
    image: postgres:15
    container_name: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: flightdb
  volumes:
    - postgres_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  restart: unless-stopped


